# Compare the 17 symbols from the 2026-09-23 13:29 BUY scan on the exact completed 2H bar.
exec(open("diagnose_tv_supertrend_formula_14.py").read().replace(
'SYMBOLS=["BIST:CLEBI","BIST:EMNIS","BIST:EUHOL","BIST:KENT","BIST:KERVN","BIST:KLYPV","BIST:KRPLS","BIST:KSTUR","BIST:OYLUM","BIST:SODSN","BIST:TUCLK","BIST:TURSG","BIST:ULUFA","BIST:USHOL"]',
'SYMBOLS=["BIST:AYGAZ","BIST:BLUME","BIST:CMENT","BIST:DIRIT","BIST:DITAS","BIST:DOFRB","BIST:DYOBY","BIST:EKSUN","BIST:HATSN","BIST:KMPUR","BIST:KPEKS","BIST:KUVVA","BIST:ORMA","BIST:OYAYO","BIST:PENGD","BIST:PENTA","BIST:TURGG"]'
))